<?php


/**
 * @file
 * Event Callout install hooks.
 */

/**
 * Add Event Callout view, display mode.
 */
function wri_event_update_10501() {
  // Add the view.
  \Drupal::service('distro_helper.updates')
    ->installConfig('views.view.event_callout', 'wri_event_callout', 'install', 'TRUE');

  // Add the callout display mode.
  \Drupal::service('distro_helper.updates')
    ->installConfig('core.entity_view_mode.node.callout', 'wri_event_callout', 'install', 'TRUE');
}
