<?php

/**
 * @file
 * Install hooks for wri_looking_terms.
 */

use Drupal\block_content\Entity\BlockContent;

/**
 * Implements hook_install().
 *
 * Creates the reusable "Looking for something specific?" block.
 */
function wri_looking_terms_install() {
  $block_manager = \Drupal::entityTypeManager()->getStorage('block_content');
  $uuid = '237d7839-1289-42a5-8e2d-f3032ea1a974';
  $block = $block_manager->loadByProperties(['uuid' => $uuid]);

  if (!$block) {
    BlockContent::create([
      'uuid' => $uuid,
      'type' => 'looking_for_something_specific',
      'info' => 'Looking for something specific',
      'langcode' => 'en',
      'field_title' => [
        'value' => 'Looking for something specific?',
      ],
      'field_intro' => [
        'value' => '<p>WRI works on multiple topics within [current-page:taxonomy_term:name]. To view and filter all [current-page:taxonomy_term:name] resources, explore our <a href="[wri_tokens:resources_anchor]">Resource Library Below</a>.</p>',
        'format' => 'basic_html',
      ],
      'field_explore_more' => [
        'value' => 'Explore more topics within [current-page:taxonomy_term:name]',
        'format' => 'basic_html',
      ],
      'reusable' => TRUE,
    ])->save();
  }
}
