<?php

/**
 * @file
 * Contains wri_engagement.module.
 */

use Drupal\node\NodeInterface;
use Drupal\webform\Entity\Webform;

/**
 * Implements hook_theme().
 */
function wri_engagement_theme() {
  $theme = [];
  $theme['download_modal'] = [
    'variables' => [
      'content' => [],
      'webform_url' => '',
      'webform_title' => FALSE,
      'classes' => 'files-overlay-trigger',
    ],
    'template' => 'download-modal',
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function wri_engagement_preprocess_download_modal(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $interrupter_webform = FALSE;

  if ($node instanceof NodeInterface) {
    $nid = $node->id();
    // Do whatever you need to do with the node ID here...
  }
  $interrupter_webform_id = Drupal::config('wri_engagement.settings')->get('download_interrupter');
  if ($interrupter_webform_id) {
    $interrupter_webform = Webform::load($interrupter_webform_id);
  }
  $variables['#attached']['library'][] = 'wri_engagement/modal_cookie';
  if ($interrupter_webform) {
    $variables['webform_url'] = $interrupter_webform->url();
    if ($nid) {
      $variables['webform_url'] .= '?source_entity_type=node&source_entity_id=' . $nid;
      $variables['classes'] = 'webform-dialog webform-dialog-normal';
    }
  }
  else {
    $variables['webform_url'] = '/node/' . $nid . '/download';
    $variables['webform_title'] = t('Download Publication');
    $variables['classes'] = 'use-ajax';
  }

}
