<?php

/**
 * @file
 * Wri Node module code.
 */

use Drupal\wri_node\General;
use Drupal\node\NodeInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_hook().
 */
function wri_node_preprocess_wri_page_hero(&$context) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if (!$node) {
    $node_route = \Drupal::routeMatch()->getRawParameter('section_storage');
    $node_id = str_replace('node.', '', $node_route);
    $node = Node::load($node_id);
  }
  if ($node instanceof NodeInterface) {
    if (isset($node->field_main_image->entity->field_media_image->entity->uri->value)) {
      $uri = $node->field_main_image->entity->field_media_image->entity->uri->value;
      $settings = [
        'uri' => $uri,
        'lazy' => 'blazy',
        'responsive_image_style_id' => 'landing_page_hero',
      ];

      $build = [
        '#theme' => 'blazy',
        '#settings' => $settings,
        '#attached' => ['library' => ['blazy/load']],
      ];
      $context['content']['hero_image'] = $build;
      General::$htmlClasses[] = 'transparent-header white';
    }
    else {
      $context['content']['hero_image'] = [];
    }
    $context['content']['title']['#markup'] = isset($node->field_long_title->value) ? check_markup($node->field_long_title->value, 'basic_html') : $node->getTitle();
    $context['content']['intro']['#markup'] = isset($node->field_intro->value) ? check_markup($node->field_intro->value, 'basic_html') : '';
  }
}
