<?php

/**
 * @file
 * WRI admin functions.
 */

/**
 * Implements hook_page_attachments().
 */

use Drupal\media\Entity\Media;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\node\Entity\Node;

/**
 * Implements hook_page_attachments().
 */
function wri_admin_page_attachments(array &$attachments) {
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  if ($theme == 'claro') {
    // A few css/js changes to make the backend easier to use.
    $attachments['#attached']['library'][] = 'wri_admin/admin';
  }
}

/**
 * Implements hook_form_alter().
 */
function wri_admin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $layout_forms = [
    'layout_builder_configure_block',
    'node_layout_builder_form',
    'entity_view_display_layout_builder_form',
    'layout_builder_revert_overrides',
    'layout_builder_discard_changes',
  ];
  $simple_popup_forms = [
    'simple_popup_blocks_add_form',
    'simple_popup_blocks_edit_form',
  ];
  $build_info = $form_state->getBuildInfo();
  if (isset($build_info['base_form_id']) && in_array($build_info['base_form_id'], $layout_forms)) {
    $form['#attached']['library'][] = 'wri_admin/admin';
  }
  elseif (in_array($form_id, $layout_forms)) {
    $form['#attached']['library'][] = 'wri_admin/admin';
  }
  elseif (in_array($form_id, $simple_popup_forms)) {
    // Hiding the minimize option -- it's confusing.
    $form['minimize']['#access'] = FALSE;
    // Adding help text about the Center option being preferred.
    $form["layout"]['#description'] = t('For most cases for WRI, the recommended option is "Center"');
    // Adding a note about a cache clear.
    $form['submit']['#suffix'] = t('Note: You may need to clear the cache to see this change on the front end.');
  }
  elseif ($form_id == 'content_moderation_entity_moderation_form') {
    $node = $form_state->get('entity');
    if ($node && $node instanceof Node) {
      $published_node = Node::load($node->id());
      $form['link_to_revision'] = [
        '#title' => t('Compare to published'),
        '#type' => 'link',
        '#attributes' => [
          'target' => '_blank',
        ],
        '#url' => Url::fromRoute('diff.revisions_diff',
          [
            'node' => $node->id(),
            'left_revision' => $published_node->getLoadedRevisionId(),
            'right_revision' => $node->getLoadedRevisionId(),
            'filter' => 'visual_inline',
          ]
        ),
      ];
    }
  }
  if (strpos($form_id, 'media_') === 0) {
    $form['#validate'][] = 'wri_admin_validate_media_name';
  }
}

/**
 * Implements hook_theme().
 */
function wri_admin_theme() {
  $theme['entity_moderation_form__diff'] = [
    'base hook' => 'entity_moderation_form',
  ];

  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function wri_admin_theme_suggestions_entity_moderation_form(array $variables) {
  $suggestions = [];

  $suggestions[] = 'entity_moderation_form__diff';

  return $suggestions;
}

/**
 * Validation function to ensure the media name is not just numbers.
 */
function wri_admin_validate_media_name(array &$form, FormStateInterface $form_state) {
  // Check if the 'name' field exists in the form state.
  $name_values = $form_state->getValue('name');
  if (!isset($name_values[0]['value']) || empty($name_values[0]['value'])) {
    $name_values = $form_state->getValue("media")[0]["fields"]["name"] ?? NULL;
  }

  if (!isset($name_values[0]['value']) || empty($name_values[0]['value'])) {
    return;
  }

  // Extract and clean up the media name.
  $name = trim($name_values[0]['value']);
  $name_without_extension = pathinfo($name, PATHINFO_FILENAME);

  // Ensure the name contains at least one letter or dash.
  if (!preg_match('/[a-zA-Z-]/', $name_without_extension)) {

    // Ensure the form contains the 'name' field before setting an error.
    if (isset($form['name'])) {
      $form_state->setErrorByName('name', t('The media name must contain at least one letter or dash (-). Only numbers and underscores (_) are not allowed.'));
    }
    elseif (isset($form["media"][0]["fields"]["name"])) {
      $form_state->setErrorByName("media][0][fields][name", t('The media name must contain at least one letter or dash (-). Only numbers and underscores (_) are not allowed.'));
    }
  }
}
