<?php

/**
 * @file
 * The wri_zoom.module alters.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function wri_zoom_webform_submission_insert(EntityInterface $entity) {
  $params = session_get_cookie_params();
  if (isset($entity->getData()['email'])) {
    setcookie('ap3c_track_email', $entity->getData()['email'], time() + 31556952, '/', $params['domain'], FALSE, FALSE);
  }
}
