<?php

/**
 * @file
 * Functions for wri custom blocks.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_preprocess_block().
 */
function wri_block_preprocess_block(array &$variables) {
  // Custom Blocks added through layout builder are missing classes and
  // contextual links. This preprocess hook adds them back.
  // @see https://www.drupal.org/project/drupal/issues/2407761#comment-13414693
  if (isset($variables["content"]["#block_content"])) {
    // Add the block bundle.
    $variables['attributes']['class'][] = 'block-content--type-' . Html::getClass($variables["derivative_plugin_id"]);
    // We're only adding contextual links for reusable blocks. Might be nice
    // To add a link to the layout builder for non-contextuals...
    if ($variables["content"]["#block_content"]->isReusable() && isset($variables["content"]["#contextual_links"])) {
      $variables['attributes']['class'][] = 'contextual-region';

      $variables['title_suffix']['contextual_links'] = [
        '#type' => 'contextual_links_placeholder',
        '#id' => _contextual_links_to_id($variables["content"]['#contextual_links']),
      ];
    }

    // Cheap way to get the block label into the block_content render.
    if (isset($variables["content"]["block_label"][0][0])) {
      $variables["content"]["block_label"][0][0]['#markup'] = $variables["label"];
      unset($variables['label']);
    }

  }

  // Add title_attributes from this block into the title_attributes variable.
  if (isset($variables['content']['#title_attributes'])) {
    foreach ($variables['content']['#title_attributes'] as $key => $title_attribute) {
      if (isset($variables['title_attributes'][$key])) {
        $variables['title_attributes'][$key] = array_merge($variables['title_attributes'][$key], $title_attribute);
      }
      else {
        $variables['title_attributes'][$key] = $title_attribute;
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function wri_block_form_alter(&$variables) {
  // If the destination of this request is an entity browser, don't show the
  // "Save and configure" button.
  $destination = \Drupal::request()->get('destination');
  if (isset($variables["actions"]["configure_block"]) && str_starts_with($destination, '/entity-browser/')) {
    $variables["actions"]["configure_block"]['#access'] = FALSE;
  }
}
