<?php
function wri_publication_preprocess_wri_publication_columns(&$context)
{

  $node = \Drupal::routeMatch()->getParameter('node');
  $context['show_narrative_taxonomy'] = TRUE;
  if ($node instanceof \Drupal\node\NodeInterface) {
    $cutOffDate = strtotime('01/01/2020');
    $created = $node->getCreatedTime();
    $context['display_type'] = 'simple';
    $context['node_type'] = $node->getType();

    switch ($node->getType()) {
      case 'project_detail':
        $context['display_type'] = 'robust';
        break;

      case 'publication':
        if ($node->get('field_publication_display')->getString() == 'robust') {
          $context['display_type'] = 'robust';
        }

        if ($cutOffDate > $created) {
          $context['show_narrative_taxonomy'] = FALSE;
        }
        break;

      case 'data':
        if ($cutOffDate > $created) {
          $context['show_narrative_taxonomy'] = FALSE;
        }
        break;
    }
  }
}
