<?php

/**
 * @file
 * Update hooks for wri_page.
 */

/**
 * Insights Landing page updates.
 */
function wri_page_update_10600() {
  \Drupal::service('distro_helper.updates')->updateConfig('core.entity_form_display.node.page.default', [
    'dependencies#config',
    'dependencies#module',
    'content#field_long_title',
    'content#field_main_image',
    'content#field_metatags',
    'content#title',
    'hidden',
  ], 'wri_page');
}
