<?php

/**
 * @file
 * WRI Language Select module file.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function wri_language_select_preprocess_links__language_block(&$variables) {
  // Disable links for languages that don't have translations available.
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node) {
    foreach (array_keys($variables['links']) as $lang) {
      if (!$node->hasTranslation($lang)) {
        unset($variables['links'][$lang]);
      }
    }
  }
}
