block.settings.wri_taxonomy_topic_pages_resource_section_link:
  type: block_settings
  label: 'Topic pages resource section link block'
  mapping:
    link_title:
      type: string
      label: 'Link title'

# Schema for the configuration files of the WRI taxonomy module.
wri_taxonomy.settings:
  type: config_object
  label: 'WRI taxonomy settings'
  mapping:
    enable_canonical_urls:
      type: boolean
      label: 'Enable canonical urls'
    resources_anchor:
      type: string
      label: 'On-page Resources anchor'
      constraints:
        Regex:
          pattern: '/^[a-zA-Z0-9][a-zA-Z0-9-]*$/'
          message: "The %value anchor must contain only letters, numbers, and dashes, and cannot start with a dash or the '#' character."
