cache:
  http:
    s_maxage: 86400
    404_max_age: 300
    302_max_age: 300
    301_max_age: 3600
    5xx_max_age: 60
    stale_while_revalidate: 300
    stale_if_error: 86400
    vary: ''
    mustrevalidate: false
    nocache: false
    nostore: false
  surrogate:
    maxage: 86400
    nostore: false
