<?php

/**
 * @file
 * Contains wri_taxonomy.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\taxonomy\TermInterface;
use Drupal\Core\Url;

function wri_toc_theme() {
  $items['table_of_contents'] = [
    'variables' => [
      'value' => '',
      'menu_link' => '',
      'menu_title' => 'page-hierarchies',
      'node_title' => '',
      'color_class' => 'black-bar'
    ],
    'template' => 'toc',
  ];
  return $items;
}
