<?php

/**
 * @file
 * Contains wri_taxonomy.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\taxonomy\TermInterface;
use Drupal\Core\Url;

function wri_toc_theme() {
  $items['table_of_contents'] = [
    'render element' => 'elements',
    'template' => 'toc',
  ];
  return $items;
}
