<?php

/**
 * @file
 * Happening Now install and update hooks.
 */

/**
 * Translatable field update.
 */
function wri_happening_now_update_10301() {
  \Drupal::service('distro_helper.updates')->updateConfig('field.field.block_content.hero.field_hero_type', [
    'translatable',
  ], 'wri_happening_now');
  \Drupal::service('distro_helper.updates')->updateConfig('field.field.paragraph.happening_now.field_listing', [
    'translatable',
  ], 'wri_happening_now');
}
