# Schema for the configuration files of the WRI article module.
wri_article.settings:
  type: config_object
  label: 'WRI article settings'
  mapping:
    enable_main_content_b:
      type: boolean
      label: 'Default to main_content_b'
      constraints:
        NotNull: [ ]
    technical_perspective_template:
      type: sequence
      label: 'Technical Perspective template for root terms'
      sequence:
        type: integer
        label: 'Term ID'
    update_template:
      type: sequence
      label: 'Update template for root terms'
      sequence:
        type: integer
        label: 'Term ID'
    news_template:
      type: sequence
      label: 'News template for root terms'
      sequence:
        type: integer
        label: 'Term ID'
    technical_perspective_template_child_field:
      type: sequence
      label: 'Technical Perspective template for child terms'
      sequence:
        type: integer
        label: 'Term ID'
    update_template_child_field:
      type: sequence
      label: 'Update template for child terms'
      sequence:
        type: integer
        label: 'Term ID'
    news_template_child_field:
      type: sequence
      label: 'News template for child terms'
      sequence:
        type: integer
        label: 'Term ID'
