wri_node.settings:
  type: config_object
  label: 'WRI settings'
  mapping:
    unpublished_person_phrase:
      type: text
      label: 'Unpublished Person phrase'
    person_listing_url:
      type: path
      label: 'Person listing url'
    use_fallback_image:
      type: boolean
      label: 'Use a fallback image?'
    disable_ads_data_redaction:
      type: boolean
      label: 'Disable google consent mode?'
    disable_osano_script:
      type: boolean
      label: 'Disable Osano script from loading in Head?'
    twitter_share_suffix:
      type: text
      label: 'Twitter Share suffix'
    narrative_taxonomy_org_name:
      type: text
      label: 'Narrative taxonomy organization name'
    and_phrase:
        type: text
        label: 'And word for listings, ie: 1, 2 "and" 3'
    within_phrase:
      type: text
      label: 'And word for "within" in the phrase "is part of X-project within Y-topic"'

